---
name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }} - ${{ matrix.version }}
    strategy:
      matrix:
        dir: [., ./store/awsrds, ./store/vault]
        version: [1.23, 1.24]
        include:
          - dir: .
            name: go-db-credential-refresh
          - dir: ./store/awsrds
            name: store/awsrds
          - dir: ./store/vault
            name: store/vault
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: ${{ matrix.dir }}/go.sum
      - name: Test
        working-directory: ${{ matrix.dir }}
        run: go test -mod=readonly ./... -coverprofile=coverage.txt
      - name: Coverage
        uses: codecov/codecov-action@v5
        with:
          files: ${{ matrix.dir }}/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
